---
title: "Evolang_similarity"
author: "Šárka Kadavá"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intro

This is an R Markdown for similarity analysis of sound signal.

First we setup our folders

```{r folders, echo=FALSE}

#get current drive
curfolder   <- dirname(getwd())
project_folder <- paste0(curfolder, "/sound_similarity/")
dataset_folder <- paste0(project_folder, "/datasets/")
audio_path  <- paste0(project_folder, "segments/")
audio_files <- list.files(audio_path,
                         pattern = "*.wav",
                         recursive = TRUE,
                         all.files = FALSE,
                         full.names = TRUE)

print(curfolder)
print(audio_path)
```
```{r duration}

# Replace 'your_file.txt' with the path to your .txt file
txt_path <- paste0(project_folder, "duration_log.txt")

# Use read.table if the file is tab-separated or has a different delimiter
# For comma-separated files, you can use read.csv
# Set the 'sep' argument accordingly to specify the delimiter
# In this example, I assume the file is tab-separated
data_df <- read.table(txt_path, header = FALSE, sep = '\t')

# Print the first few rows of the data frame to check the import
head(data_df)

# What is the minimum duration
min(data_df$V5) #18 ms
mean(data_df$V5) # 354 ms


```



## Extracting features from sound

We use package 'soundgen' to extract a package of features for sound signal
More info here: https://www.rdocumentation.org/packages/soundgen/versions/2.6.0 or here: https://cogsci.se/soundgen/acoustic_analysis.html

```{r soundgen}

library(soundgen)
#library(tuneR)

# Create an empty data frame to store the features
feature_df <- data.frame()

# Create a function to extract summary features from the analyze output
extract_summary_features <- function(file, analyze_result) {
  summary_features <- analyze_result$summary
  # Add the filename as the first column
  summary_features <- cbind(File = file, summary_features)
  return(summary_features)
}

# Loop over the .wav files in the directory and extract summary features
for (file in audio_files) {
  # Check if the file name ends with '_p ', and skip processing if it does
  if (endsWith(file, "_p .wav")) {
    print(paste("Skipping file:", file))
    next  # Skip this file and continue with the next iteration
  }
  print(paste("Analyzing file:", file))
  #audio <- readWave(file)
  features <- analyze(file, samplingRate = 44100, windowLength = 10, step = 5)
  
  # Extract and format summary features
  summary_features_df <- extract_summary_features(file, features)
  
  # Append the summary features for this file to the main data frame
  feature_df <- rbind(feature_df, summary_features_df)
}

# Reset row names and remove them
row.names(feature_df) <- NULL

# Print the data frame with features
print(feature_df)

# Create the full file path including the folder and file name
output_file <- paste0(dataset_folder, "/segments_soundgen_summary.csv")

# Save the data frame as a CSV file
write.csv(feature_df, file = output_file, row.names = FALSE)
```





